name: apical
description: "Apical"
version: 0.0.2


environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.0

  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cookie_manager: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
